### ISSUE TITLE
Cannot create DB user on DB server with remote access rights

### ISSUE THREAD

**Issue by hhhc** [ploi/ploi-php-sdk#75]
I setup a database server and create the users via script (php api sdk), like this:

    $db = $this->ploi->servers($serverId)->databases()->create(
        $databaseName,
        $databaseUser,
        $databaseUserPassword,
        $description
    )->getJson();

Unfortunately, the created users are not allowed to access remotely. Checking the API docs (https://github.com/ploi/ploi-php-sdk) as well as the source code

https://github.com/ploi/ploi-php-sdk/blob/master/src/Ploi/Resources/Database.php 
https://github.com/ploi/ploi-php-sdk/blob/master/src/Ploi/Resources/DatabaseUser.php

I do not find how to add a remote user. It would be great if that could be added.

**Comment by Cannonb4ll** [comment]
Fixed in version 1.9.2 🤝
