### ISSUE TITLE
Best way to delete site and all of it's data

### ISSUE THREAD

**Issue by Dynalogical** [ploi/ploi-php-sdk#77]
I always get the error: 

`{"message":"The given data was invalid.","errors":["There are still sites running on this user, please remove\/detach these first."],"links":[]}`

I use the code below to destroy the components, but I always get the same error, even though the statuscode is 200.

```
//DESTROY DATABASE
$ploi->server($sites->server_id)->databases($sites->database->database_id)->delete();

//DESTROY SITE
$site = $ploi->server($sites->server_id)->sites($sites->site_id)->delete()->getResponse();

if ($site->withStatus(200)) {
    //DESTROY USER
    $ploi->server($sites->server_id)->systemUsers($sites->user->user_id)->delete();
}
```

**Comment by fodderstompf** [comment]
I think it's down to Ploi running the delete site over a queue, so it's not finished deleting at the time you send the next request.

**Comment by Dynalogical** [comment]
> I think it's down to Ploi running the delete site over a queue, so it's not finished deleting at the time you send the next request.

Yeah that's what I figured, so I set up a cronjob that removes the user after a period of time. Seems to be working fine.
